-- CreateTable
CREATE TABLE `Registration` (
    `id` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `registrationNo` VARCHAR(191) NOT NULL,
    `date` DATETIME(3) NOT NULL,
    `headFirstName` VARCHAR(191) NOT NULL,
    `headLastName` VARCHAR(191) NULL,
    `headName` VARCHAR(191) NOT NULL,
    `residentType` VARCHAR(191) NOT NULL,
    `gender` VARCHAR(191) NOT NULL,
    `blockNo` VARCHAR(191) NOT NULL,
    `flatNo` VARCHAR(191) NOT NULL,
    `dob` DATETIME(3) NULL,
    `bloodGroup` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `profession` VARCHAR(191) NULL,
    `mobileNo` VARCHAR(191) NOT NULL,
    `whatsappNo` VARCHAR(191) NULL,
    `totalMembers` INTEGER NULL,
    `photoUrl` VARCHAR(191) NULL,
    `familyMembers` JSON NULL,
    `emergency` JSON NULL,
    `twoWheelerCount` INTEGER NULL,
    `fourWheelerCount` INTEGER NULL,
    `twoWheelers` JSON NULL,
    `fourWheelers` JSON NULL,
    `agree` BOOLEAN NOT NULL DEFAULT false,

    UNIQUE INDEX `Registration_registrationNo_key`(`registrationNo`),
    INDEX `Registration_blockNo_flatNo_idx`(`blockNo`, `flatNo`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
